version : '3.8'

services:
  app:
    build: .
    container_name: chatbot
    environment:
      AWS_REGION : ${AWS_REGION}
      USER_POOL_ID : ${USER_POOL_ID}
      CLIENT_ID : ${CLIENT_ID}
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
      DYNAMO_DB_TABLE : ${DYNAMO_DB_TABLE}
      TABLE_NAME_USER : userapp
      TABLE_NAME_CONVERSATION : conversations
      TABLE_NAME_CONVERSATION_MESSAGES : messages
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: db  
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      MODEL_NAME :  ${MODEL_NAME}
      TEMPERATURE  : ${TEMPERATURE}
      OPENAI_API_KEY  : ${OPENAI_API_KEY}