DEBUG_MODE = False
DB_PATH = "./db_test"
COLLECTION_NAME = "Collection1"
MODEL_NAME = "manu/sentence_croissant_alpha_v0.4"
FILENAME_DATASET_RAG = "./data/dataset_RAG.xlsx"

TABLE_USER = "users"
TABLE_CONVERSATIONS = "conversations"
TABLE_CONVERSATION_MESSAGES = "conversation_messages"
TABLE_PACKAGE = "package"
TABLE_LANGUAGE = "language"
TABLE_COVERAGE_TYPE = "coverage_type"
TABLE_PACKAGE_LANGUAGE = "package_language"
TABLE_PACKAGE_DESCRIPTION = "package_description"
TABLE_USER_INSURANCE = "user_insurances"

COL_INDEX = "index"
COL_TEXT = "text"
COL_TYPE = "type"
COL_CATEGORY = "category"
COL_PACKAGE = "package"
COL_ARTICLE = "article"
COL_COMPANY = "company"
COL_EMBEDDINGS = "embeddingd"
